
package com.banktowallet.b2w.b2w;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "B2WServices", targetNamespace = "http://b2w.banktowallet.com/b2w")
@XmlSeeAlso({
    com.banktowallet.b2w.b2w.ObjectFactory.class,
    com.banktowallet.b2w.b2w._1.ObjectFactory.class
})
public interface B2WServices {


    /**
     * 
     * @param tranRequestInfo
     * @return
     *     returns com.banktowallet.b2w.b2w.CancelTransferResponse.Return
     */
    @WebMethod(operationName = "CancelTransfer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "CancelTransfer", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.CancelTransfer")
    @ResponseWrapper(localName = "CancelTransferResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.CancelTransferResponse")
    public com.banktowallet.b2w.b2w.CancelTransferResponse.Return cancelTransfer(
        @WebParam(name = "TranRequestInfo", targetNamespace = "")
        com.banktowallet.b2w.b2w.CancelTransfer.TranRequestInfo tranRequestInfo);

    /**
     * 
     * @param mobileTransferRequest
     * @return
     *     returns com.banktowallet.b2w.b2w.AccountToWalletTransferResponse.Return
     */
    @WebMethod(operationName = "AccountToWalletTransfer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AccountToWalletTransfer", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.AccountToWalletTransfer")
    @ResponseWrapper(localName = "AccountToWalletTransferResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.AccountToWalletTransferResponse")
    public com.banktowallet.b2w.b2w.AccountToWalletTransferResponse.Return accountToWalletTransfer(
        @WebParam(name = "MobileTransferRequest", targetNamespace = "")
        com.banktowallet.b2w.b2w.AccountToWalletTransfer.MobileTransferRequest mobileTransferRequest);

    /**
     * 
     * @param mobileTransferRequest
     * @return
     *     returns com.banktowallet.b2w.b2w.WalletToAccountTransferResponse.Return
     */
    @WebMethod(operationName = "WalletToAccountTransfer")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "WalletToAccountTransfer", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.WalletToAccountTransfer")
    @ResponseWrapper(localName = "WalletToAccountTransferResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.WalletToAccountTransferResponse")
    public com.banktowallet.b2w.b2w.WalletToAccountTransferResponse.Return walletToAccountTransfer(
        @WebParam(name = "MobileTransferRequest", targetNamespace = "")
        com.banktowallet.b2w.b2w.WalletToAccountTransfer.MobileTransferRequest mobileTransferRequest);

    /**
     * 
     * @param accountBalanceInquiryRequest
     * @return
     *     returns com.banktowallet.b2w.b2w.GetAccountBalanceResponse.Return
     */
    @WebMethod(operationName = "GetAccountBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetAccountBalance", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.GetAccountBalance")
    @ResponseWrapper(localName = "GetAccountBalanceResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.GetAccountBalanceResponse")
    public com.banktowallet.b2w.b2w.GetAccountBalanceResponse.Return getAccountBalance(
        @WebParam(name = "AccountBalanceInquiryRequest", targetNamespace = "")
        com.banktowallet.b2w.b2w.GetAccountBalance.AccountBalanceInquiryRequest accountBalanceInquiryRequest);

    /**
     * 
     * @param tranRequestInfo
     * @return
     *     returns com.banktowallet.b2w.b2w.TransferStatusInquiryResponse.Return
     */
    @WebMethod(operationName = "TransferStatusInquiry")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TransferStatusInquiry", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.TransferStatusInquiry")
    @ResponseWrapper(localName = "TransferStatusInquiryResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.TransferStatusInquiryResponse")
    public com.banktowallet.b2w.b2w.TransferStatusInquiryResponse.Return transferStatusInquiry(
        @WebParam(name = "TranRequestInfo", targetNamespace = "")
        com.banktowallet.b2w.b2w.TransferStatusInquiry.TranRequestInfo tranRequestInfo);

    /**
     * 
     * @param miniStatementRequest
     * @return
     *     returns com.banktowallet.b2w.b2w.GetMiniStatementResponse.Return
     */
    @WebMethod(operationName = "GetMiniStatement")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetMiniStatement", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.GetMiniStatement")
    @ResponseWrapper(localName = "GetMiniStatementResponse", targetNamespace = "http://b2w.banktowallet.com/b2w", className = "com.banktowallet.b2w.b2w.GetMiniStatementResponse")
    public com.banktowallet.b2w.b2w.GetMiniStatementResponse.Return getMiniStatement(
        @WebParam(name = "MiniStatementRequest", targetNamespace = "")
        com.banktowallet.b2w.b2w.GetMiniStatement.MiniStatementRequest miniStatementRequest);

}
